/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.clinica_medica.view.administrador;

import br.edu.imepac.clinica_medica.dao.ConvenioDao;
import br.edu.imepac.clinica_medica.dao.EspecialidadeDao;
import br.edu.imepac.clinica_medica.dao.FuncionarioDao;
import br.edu.imepac.clinica_medica.dao.UsuarioDao;
import br.edu.imepac.clinica_medica.model.Usuario;
import br.edu.imepac.clinica_medica.service.login.SessaoUsuario;
import br.edu.imepac.clinica_medica.view.login.TelaLogin;
import java.awt.event.ActionEvent;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Mateus
 */
public class MenuAdministrador extends javax.swing.JFrame {

    private Usuario usuario;
private FuncionarioDao funcionarioDao;
    private UsuarioDao usuarioDao;
    private EspecialidadeDao especialidadeDao;
    private ConvenioDao convenioDao;
    
    public MenuAdministrador(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
       this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
      funcionarioDao = new FuncionarioDao();
        usuarioDao = new UsuarioDao();
        especialidadeDao = new EspecialidadeDao();
        convenioDao = new ConvenioDao();

        initComponents();
        this.usuario = null; // ou crie um usuário padrão, se necessário
        // Inicializa os DAOs também no construtor sem usuário, se for usado
        funcionarioDao = new FuncionarioDao();
        usuarioDao = new UsuarioDao();
        especialidadeDao = new EspecialidadeDao();
        convenioDao = new ConvenioDao();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        menuFuncionario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuEspecialidades = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        menuMedico = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        menuConvenios = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        menuPerfil = new javax.swing.JMenu();
        menuDoPerfil = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuFuncionario.setText("Funcionario");

        jMenuItem1.setText("Cadastrar funcionario");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuFuncionario.add(jMenuItem1);

        jMenuItem2.setText("Listar funcionario");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuFuncionario.add(jMenuItem2);

        jMenuBar2.add(menuFuncionario);

        menuEspecialidades.setText("Especialidades");

        jMenuItem3.setText("Cadastrar especialidades");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuEspecialidades.add(jMenuItem3);

        jMenuItem4.setText("Listar especialidades");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuEspecialidades.add(jMenuItem4);

        jMenuBar2.add(menuEspecialidades);

        menuUsuario.setText("Usuario");
        menuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioActionPerformed(evt);
            }
        });

        jMenuItem5.setText("Cadastrar usuario");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem5);

        jMenuItem6.setText("Listar usuario");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuUsuario.add(jMenuItem6);

        jMenuBar2.add(menuUsuario);

        menuMedico.setText("Medico");

        jMenuItem7.setText("Cadastrar medico");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuMedico.add(jMenuItem7);

        jMenuItem8.setText("Listar medico");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        menuMedico.add(jMenuItem8);

        jMenuBar2.add(menuMedico);

        menuConvenios.setText("Convenios");

        jMenuItem9.setText("Cadastrar convenio");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuConvenios.add(jMenuItem9);

        jMenuItem10.setText("Listar convenio");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        menuConvenios.add(jMenuItem10);

        jMenuBar2.add(menuConvenios);

        menuPerfil.setText("Perfil");

        menuDoPerfil.setText("Editar perfil");
        menuDoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDoPerfilActionPerformed(evt);
            }
        });
        menuPerfil.add(menuDoPerfil);

        jMenuBar2.add(menuPerfil);

        menuSistema.setText("Sistema");

        jMenuItem12.setText("Logout");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        menuSistema.add(jMenuItem12);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuSistema.add(menuSair);

        jMenuBar2.add(menuSistema);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastrarFuncionario cadastrarFuncionarioTela = new CadastrarFuncionario ();
        cadastrarFuncionarioTela.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
         System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuDoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDoPerfilActionPerformed
         EditarPerfil ep = new EditarPerfil();
    ep.setVisible(true);
    }//GEN-LAST:event_menuDoPerfilActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       ListarFuncionario listarFuncionariosTela = new ListarFuncionario();
    listarFuncionariosTela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        CadastrarEspecialidade telaCadastro = new CadastrarEspecialidade();
        telaCadastro.setVisible(true);
        telaCadastro.setLocationRelativeTo(null);  
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        ListarEspecialidade telaListar = new ListarEspecialidade();
        telaListar.setVisible(true);
        telaListar.setLocationRelativeTo(null);   
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void menuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioActionPerformed
        CadastrarUsuario TelaCadastroUsuario = new CadastrarUsuario();
        TelaCadastroUsuario.setVisible(true);
        TelaCadastroUsuario.setLocationRelativeTo(null);
    }//GEN-LAST:event_menuUsuarioActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       new ListarUsuario().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        CadastrarConvenio telaCadastrarConvenio = new CadastrarConvenio();
        telaCadastrarConvenio.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        ListarConvenio tela = new ListarConvenio();
tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CadastrarMedico tela = new CadastrarMedico();
tela.setVisible(true);     
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
     ListarMedico tela = new ListarMedico();
tela.setVisible(true); 
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
int confirmar = JOptionPane.showConfirmDialog(this, "Deseja realmente sair?", "Logout", JOptionPane.YES_NO_OPTION);
    
    if (confirmar == JOptionPane.YES_OPTION) {
        SessaoUsuario.limpar(); // Limpa o usuário logado
        this.dispose(); // Fecha a janela atual

        // Retorna para a tela de login
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
    }        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       CadastrarUsuario telaCadastrarUsuario = new CadastrarUsuario();
       telaCadastrarUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Usuario usuarioLogado = new Usuario(); // ou receba de outro lugar, como da tela de login

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador(usuarioLogado).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenu menuConvenios;
    private javax.swing.JMenuItem menuDoPerfil;
    private javax.swing.JMenu menuEspecialidades;
    private javax.swing.JMenu menuFuncionario;
    private javax.swing.JMenu menuMedico;
    private javax.swing.JMenu menuPerfil;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables

}
